### ISSUE TITLE
Improve the tests

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-host-inventory#195]
This is an umbrella task listing the issues with the current state of tests. There are many and can be solved incrementally. Let’s not forget about them.

* [ ] Make the tests structured – modules, subfolders… #102
* [ ] Get rid of the [_HostWrapper_](https://github.com/RedHatInsights/insights-host-inventory/blob/5f7f494c5c932487450b794b85b3c169dca242f1/app/utils.py#L4) class and its [_utils_](https://github.com/RedHatInsights/insights-host-inventory/blob/5f7f494c5c932487450b794b85b3c169dca242f1/app/utils.py) module #194
* [ ] Fix notoriously failing tests #101
* [ ] Use a separate database for testing #20

**Comment by Glutexo** [comment]
Pytest, fixtures…
