### ISSUE TITLE
Create a health check endpoint

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-host-inventory#46]
The application needs a health check endpoint simply returning _200_ to any _GET_ request.

The health check request must not require authentication. Thus it’s necessary to allow unauthenticated operations (#50) in the first place. Everything up to the real-world usage is reviewable and mergeable even now though.

* [x] Create a health check endpoint (#39)
* [x] Document the health check endpoint (#49)
* [x] Enable a health probe on the deployed instance

Pull requests:

* [x] #39 **ready for a review**
* [x] #49 waiting for #39 to get reviewed and merged

**Comment by Glutexo** [comment]
Created a new PR #47 based on #38 and #45. It adds functional tests to #38, which requires #45.

**Comment by Glutexo** [comment]
Rebased all the pull requests (#38, #39, #45 and #41) on the [current _master_](https://github.com/RedHatInsights/insights-host-inventory/tree/53768932260e9e9ab8924718ec7667fd9dceb3be). #38, #39 and #47 are ready for a review. Asking @dehort for those. After that, #47 and #41 will become reviewable.

**Comment by Glutexo** [comment]
Created #49 based on #41. It documents the health check endpoint in the [README](
https://github.com/RedHatInsights/insights-host-inventory/pull/49/files#diff-04c6e90faac2675aa89e2176d2eec7d8).

**Comment by Glutexo** [comment]
#38 got dropped as we’re going to take a different approach to the unauthenticated operations: the identity header won’t be required by default. That means that the health probe won’t require authentication as it won’t be explicitly marked so.

**Comment by Glutexo** [comment]
Done. closing.
