### ISSUE TITLE
Allow unauthenticated routes

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-host-inventory#51]
There are at least two reasons why we need to allow unauthenticated routes:

* A health check endpoint for the health probe (#46)
* The Swagger UI Console

To be compliant with the OpenAPI specification file and to avoid ugly hacks for the Swagger UI, authenticated operations must be explicitly marked. All other ones are considered not requiring the identity header.

Steps:

* [x] Support unauthenticated operations (#50)
* [ ] Allow a creation of additional operations in tests (#45)
* [ ] Test unauthenticated operations (#52)
* [ ] Mark the unauthenticated operations automatically by the OpenAPI specification (_No pull request yet_)

Pull requests:

* [x] #50 **ready for a review**, without functional tests
* [ ] #45 **ready for a review**, will allow having functional tests for #50
* [ ] #52 waiting for #50 and #45 to get reviewed and merged

**Comment by Glutexo** [comment]
Closing this as this is resolved. It’s not done automatically by reading the specification file, but that is not a priority for now. It can be done as a separate issue later.
